apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: operator-ibm-integration
  namespace: flux-system
spec:
  dependsOn:
  - name: catalog-sources
  - name: operator-common-service
  - name: ibm-platform-navigator
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kustomize/operators/ibm-integration
  prune: true
  # decryption:
    # provider: sops
    # secretRef:
      # name: sops-hcvault