apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openshift-operators
resources: 
#- license.yaml
- sub-mq.yaml
- sub-ace.yaml
- sub-apic.yaml
- sub-es.yaml
- sub-eem.yaml
- ../../config
replacements:
  - source:
      kind: ConfigMap
      name: default-config
      fieldPath: data.APIC_CHANNEL
    targets:
      - select:
          kind: Subscription
          name: "ibm-apiconnect"
        fieldPaths:
          - spec.channel
  - source:
      kind: ConfigMap
      name: default-config
      fieldPath: data.ACE_CHANNEL
    targets:
      - select:
          kind: Subscription
          name: "ibm-appconnect"
        fieldPaths:
          - spec.channel
  - source:
      kind: ConfigMap
      name: default-config
      fieldPath: data.MQ_CHANNEL
    targets:
      - select:
          kind: Subscription
          name: "ibm-mq"
        fieldPaths:
          - spec.channel
  - source:
      kind: ConfigMap
      name: default-config
      fieldPath: data.ES_CHANNEL
    targets:
      - select:
          kind: Subscription
          name: "ibm-eventstreams"
        fieldPaths:
          - spec.channel
  - source:
      kind: ConfigMap
      name: default-config
      fieldPath: data.EEM_CHANNEL
    targets:
      - select:
          kind: Subscription
          name: "ibm-eventendpointmanagement"
        fieldPaths:
          - spec.channel