apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: 
- ns.yaml
- clrb-admin-sa.yaml
- sa-admin.yaml
- job-key.yaml
- pn.yaml
- ../../config
replacements:
  - source:
      kind: ConfigMap
      name: default-config
      fieldPath: data.CP4I_LICENSE
    targets:
      - select:
          kind: PlatformNavigator
        fieldPaths:
          - spec.license.license
  - source:
      kind: ConfigMap
      name: default-config
      fieldPath: data.CP4I_VERSION
    targets:
      - select:
          kind: PlatformNavigator
        fieldPaths:
          - spec.version