apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: 
- ns.yaml
- job-key.yaml
- pn-16-1.yaml
vars:
  - name: CP4I_LICENSE
    objref:
      kind: ConfigMap
      name: global-config
      apiVersion: v1
    fieldref:
      fieldpath: data.cp4iLicense