apiVersion: v1
kind: Namespace
metadata:
  name: cp4i
---
apiVersion: v1
kind: Namespace
metadata:
  name: ace
---
apiVersion: v1
kind: Namespace
metadata:
  name: apic
---
apiVersion: v1
kind: Namespace
metadata:
  name: event

