kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: busybox-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: gp3-csi
spec:
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
