apiVersion: integration.ibm.com/v1beta1
kind: AssetRepository
metadata:
  labels:
    backup.integration.ibm.com/component: assetrepository
  name: asset-repo-ai
  namespace: cp4i
spec:
  designerAIFeatures:
    enabled: true
  license:
    accept: true
    license: L-VTPK-22YZPK
  replicas: 1
  singleReplicaOnly: true
  storage:
    assetDataVolume:
      class: gp3
    couchVolume:
      class: gp3
  version: 2023.4.1