apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: 
- ../../ibm/platform-nav/ks.yaml
- ../../ibm/api-connect/ks.yaml
#- ../../ibm/app-connect/ks.yaml
#- ../../ibm/asset-repo/ks.yaml
#- ../../ibm/mq/ks.yaml

