apiVersion: batch/v1
kind: Job
metadata:
  name: copy-key
  namespace: ace
spec:
  template:
    spec:
      containers:
      - name: copy-key
        image: bitnami/kubectl:latest
        command: ["/bin/sh", "-c"]
        args:
          - |
            kubectl get secret ibm-entitlement-key -n default -o yaml | sed 's/default/ace/g' | kubectl create -n ace -f - 
            echo "key created!"
      restartPolicy: Never