apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: 
- ns.yaml
- clrb-admin-sa.yaml
- sa-admin.yaml
- job-key.yaml
- mq-conf.yaml
- manager.yaml
patches:
- patch: |-
    - op: replace
      path: /spec/version
      value: 9.4.0.0-r1
  target:
    group: mq.ibm.com
    kind: QueueManager
    name: mainmqm
    version: v1beta1