apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-platform-nav
  namespace: flux-system
spec:
  dependsOn:
  - name:  operator-ibm-integration
  interval: 1h
  retryInterval: 1m
  healthChecks:
#   - apiVersion: apps/v1
#      kind: Deployment
#      name: cp4i-navigator-ibm-integration-platform-navigator-deployment
#      namespace: cp4i
    - apiVersion: apps/v1
      kind: PlatformNavigator
      name: cp4i-navigator
      namespace: cp4i
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kustomize/apps/ibm/platform-nav
  prune: true
  # decryption:
    # provider: sops
    # secretRef:
      # name: sops-hcvault
