apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openshift-operators
resources: 
- license.yaml
- sub.yaml
- ../../../config
replacements:
  - source:
      kind: ConfigMap
      name: default-config
      fieldPath: data.PN_CHANNEL
    targets:
      - select:
          kind: Subscription
        fieldPaths:
          - spec.channel
  - source:
      kind: ConfigMap
      name: default-config
      fieldPath: data.PN_CSV
    targets:
      - select:
          kind: Subscription
        fieldPaths:
          - spec.startingCSV