apiVersion: operator.ibm.com/v3
kind: CommonService
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    kustomize.toolkit.fluxcd.io/ssa: merge
  name: common-service
  namespace: cp4i
spec:
  license:
    accept: true
