apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-app-connect
  namespace: flux-system
spec:
  dependsOn:
  - name: operator-ibm-integration
  - name: inst-platform-nav
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kustomize/instances/ace
  prune: true
