apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-api-connect
  namespace: flux-system
spec:
  dependsOn:
  - name: operator-ibm-integration
  - name: inst-platform-nav
  interval: 1h
  retryInterval: 5m
  healthChecks:
  - apiVersion: apiconnect.ibm.com/v1beta1
    kind: APIConnectCluster
    name: apic-demo
    namespace: apic
    jsonPath: ".status.conditions[?(@.type=='Ready')].status"
    value: "True"
  timeout: 30m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kustomize/instances/apic
  prune: true
