apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apic
resources: 
- apic.yaml
- ../../config
replacements:
  - source:
      kind: ConfigMap
      name: default-config
      fieldPath: data.CP4I_LICENSE
    targets:
      - select:
          kind: APIConnectCluster
        fieldPaths:
          - spec.license.license
  - source:
      kind: ConfigMap
      name: default-config
      fieldPath: data.APIC_VERSION
    targets:
      - select:
          kind: APIConnectCluster
        fieldPaths:
          - spec.version
  - source:
      kind: ConfigMap
      name: default-config
      fieldPath: data.STORAGE_RWO
    targets:
      - select:
          kind: APIConnectCluster
        fieldPaths:
          - spec.storageClassName