apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-mq
  namespace: flux-system
spec:
  dependsOn:
  - name: operator-ibm-integration
  - name: app-platform-nav
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kustomize/apps/ibm/mq
  prune: true
  # decryption:
    # provider: sops
    # secretRef:
      # name: sops-hcvault
