apiVersion: apiconnect.ibm.com/v1beta1
kind: APIConnectCluster
metadata:
  annotations:
    apiconnect-operator/backups-not-configured: 'true'
  labels:
    app.kubernetes.io/instance: apiconnect
    app.kubernetes.io/managed-by: ibm-apiconnect
    app.kubernetes.io/name: apic-min
  name: apic-min
  namespace: cp4i
spec:
  license:
    accept: true
    license: L-MMBZ-295QZQ
    metric: VIRTUAL_PROCESSOR_CORE
    use: nonproduction
  management:
#    governance:
#      enabled: true
    testAndMonitor:
      autoTestEnabled: false
      enabled: false
  imagePullSecrets:
    - ibm-entitlement-key
  gateway:
    webGUIManagementEnabled: true
#  analytics:
#    storage:
#      enabled: true
#      type: shared
  storageClassName: gp3-csi
  profile: n1xc7.m48
  version: 10.0.7.0-5560
  imageRegistry: cp.icr.io/cp/apic