apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: 
- sub.yaml
- ns.yaml
- ../../../config
replacements:
  - source:
      kind: ConfigMap
      name: default-config
      fieldPath: data.CMS_CHANNEL
    targets:
      - select:
          kind: Subscription
        fieldPaths:
          - spec.channel
  - source:
      kind: ConfigMap
      name: default-config
      fieldPath: data.CMS_CSV
    targets:
      - select:
          kind: Subscription
        fieldPaths:
          - spec.startingCSV